spring.application.name=app

# H2 in-memory DB
spring.datasource.url=jdbc:h2:mem:weather
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Run schema.sql & data.sql
spring.sql.init.mode=always

# IMPORTANT: disable Hibernate auto table creation
spring.jpa.hibernate.ddl-auto=update

# Show SQL logs
spring.jpa.show-sql=true

# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console